# Generated by Django 4.1.7 on 2023-02-23 11:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastModifiedDate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastModifiedDate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastModifiedDate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastModifiedDate', models.DateTimeField(blank=True, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.address')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastModifiedDate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastModifiedDate', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.category')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.location')),
            ],
        ),
        migrations.CreateModel(
            name='QuantityUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastModifiedDate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastModifiedDate', models.DateTimeField(blank=True, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.address')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastModifiedDate', models.DateTimeField(blank=True, null=True)),
                ('total_value', models.FloatField(default=0)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.currency')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('quantityUnit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.quantityunit')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastModifiedDate', models.DateTimeField(blank=True, null=True)),
                ('total_value', models.FloatField(default=0)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.currency')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('quantityUnit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.address')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0)),
                ('reorderLevel', models.FloatField(default=0)),
                ('lastModifiedDate', models.DateTimeField(blank=True, null=True)),
                ('price', models.FloatField(default=0)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('quantityUnit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quantity_unit', to='products.quantityunit')),
                ('reorderQuantityUnit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reorder_quantity_unit', to='products.quantityunit')),
            ],
        ),
    ]
